Repository mapsme/omim, pull requests merged in 2018-06, with the labels that each got.

#8745 Update categories.txt
  data/categories.txt
Labels: enhancement

#8890 Add a label for leisure-dog_park
  data/categories.txt
Labels: CLA Signed, enhancement

#8941 [android] Fixed compilation
  configure.sh
Labels: CLA Signed
